// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBfT8Ngu_wAFMUxxp6YsYngdwzMCDWv2h0',
    appId: '1:377702692879:web:af20e0f45d179db9238b7a',
    messagingSenderId: '377702692879',
    projectId: 'myapp-cb06b',
    authDomain: 'myapp-cb06b.firebaseapp.com',
    storageBucket: 'myapp-cb06b.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCXU72PgnaC6TB2XrfTjCPJ31ZDoGJO4y8',
    appId: '1:377702692879:android:9b77b8a34126cd90238b7a',
    messagingSenderId: '377702692879',
    projectId: 'myapp-cb06b',
    storageBucket: 'myapp-cb06b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC_Xb6iPIqAtOtSyemA8n7mqBkSI238nl8',
    appId: '1:377702692879:ios:46f5304552f10143238b7a',
    messagingSenderId: '377702692879',
    projectId: 'myapp-cb06b',
    storageBucket: 'myapp-cb06b.appspot.com',
    iosClientId: '377702692879-evfulnjc91si4e8fts5fr1ku3684n3j7.apps.googleusercontent.com',
    iosBundleId: 'com.example.aaawwwmyapp',
  );
}
